apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginxdeployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: {{ .Release.Name }}-nginxcontainer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        ports:
        - containerPort: 80